version : 2
jobs:
  build: # required for the runs that don't use workflows
  working_directory: .
  docker:
      -image: circleci/python:2.7.6
      steps:
        - checkout
        
        - run:
          command: | #use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pipenv run python tests.py
        
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results
            destination: tr1

