jobs:
  test:
   docker:
     - image: circleci/python:2.7
   steps:
     - checkout
     - run:
         name:
         command: |
          sudo pip install -r requirements.txt
          python tests.py
     - store_test_results:
         path: build/test-results
     - store_artifacts:
         path: build/libs
         destination: prefix
     - persist_to_workspace:
         root: . #the folder to start the workspace from.
         paths:
           - .
  dockerize:
    machine : true
  steps:
     - attach_workspace:
         at: .
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
     # deploy the image
     - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1

workflows:
 version: 2
 two_job_flow:
   jobs:
     - test
     - package:
         requires:
           - test

